# -*- coding: utf-8 -*-
"""contact_management.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zUuRJ1IN7z34olrKRw_VI4Jk1EwpX0cS
"""

contacts = {}

print("Contact Management System")
print("1. Add Contact")
print("2. View Contacts")
print("3. Search Contact")
print("4. Update Contact")
print("5. Delete Contact")
print("6. Exit")

name = input("Enter contact name: ")
phone = input("Enter phone number: ")
email = input("Enter email: ")

contacts[name] = {
    "phone": phone,
    "email": email
}

print("Contact added successfully!")

print("\n--- All Contacts ---")

for name, details in contacts.items():
    print("Name:", name)
    print("Phone:", details["phone"])
    print("Email:", details["email"])
    print("-------------------")

search_name = input("Enter contact name to search: ")

if search_name in contacts:
    print("Contact Found!")
    print("Phone:", contacts[search_name]["phone"])
    print("Email:", contacts[search_name]["email"])
else:
    print("Contact not found!")

update_name = input("Enter contact name to update: ")

if update_name in contacts:
    new_phone = input("Enter new phone number: ")
    new_email = input("Enter new email: ")

    contacts[update_name]["phone"] = new_phone
    contacts[update_name]["email"] = new_email

    print("Contact updated successfully!")
else:
    print("Contact not found!")

contacts = {}

while True:
    print("\n===== Contact Management System =====")
    print("1. Add Contact")
    print("2. View Contacts")
    print("3. Search Contact")
    print("4. Update Contact")
    print("5. Delete Contact")
    print("6. Exit")

    choice = input("Enter your choice: ")

    # Add Contact
    if choice == "1":
        name = input("Enter contact name: ")
        phone = input("Enter phone number: ")
        email = input("Enter email: ")

        contacts[name] = {
            "phone": phone,
            "email": email
        }

        print("Contact added successfully!")

    # View Contacts
    elif choice == "2":
        if not contacts:
            print("No contacts available!")
        else:
            print("\n--- All Contacts ---")

            for name, details in contacts.items():
                print("Name:", name)
                print("Phone:", details["phone"])
                print("Email:", details["email"])
                print("-------------------")

    # Search Contact
    elif choice == "3":
        search_name = input("Enter contact name to search: ")

        if search_name in contacts:
            print("Contact Found!")
            print("Phone:", contacts[search_name]["phone"])
            print("Email:", contacts[search_name]["email"])
        else:
            print("Contact not found!")

    # Update Contact
    elif choice == "4":
        update_name = input("Enter contact name to update: ")

        if update_name in contacts:
            new_phone = input("Enter new phone number: ")
            new_email = input("Enter new email: ")

            contacts[update_name]["phone"] = new_phone
            contacts[update_name]["email"] = new_email

            print("Contact updated successfully!")
        else:
            print("Contact not found!")

    # Delete Contact
    elif choice == "5":
        delete_name = input("Enter contact name to delete: ")

        if delete_name in contacts:
            del contacts[delete_name]
            print("Contact deleted successfully!")
        else:
            print("Contact not found!")

    # Exit
    elif choice == "6":
        print("Thank you for using Contact Management System!")
        break

    else:
        print("Invalid choice! Please try again.")

import json

import json
import os

if os.path.exists("contacts.json"):
    with open("contacts.json", "r") as file:
        contacts = json.load(file)
else:
    contacts = {}

print("Contacts loaded successfully!")
print(contacts)

def save_contacts():
    with open("contacts.json", "w") as file:
        json.dump(contacts, file, indent=4)

    print("Contacts saved successfully!")

save_contacts()

while True:
    print("\n===== Contact Management System =====")
    print("1. Add Contact")
    print("2. View Contacts")
    print("3. Search Contact")
    print("4. Update Contact")
    print("5. Delete Contact")
    print("6. Exit")

    choice = input("Enter your choice: ")

    # Add Contact
    if choice == "1":
        name = input("Enter contact name: ")
        phone = input("Enter phone number: ")
        email = input("Enter email: ")

        contacts[name] = {
            "phone": phone,
            "email": email
        }

        save_contacts()
        print("Contact added successfully!")

    # View Contacts
    elif choice == "2":
        if not contacts:
            print("No contacts available!")
        else:
            print("\n--- All Contacts ---")

            for name, details in contacts.items():
                print("Name:", name)
                print("Phone:", details["phone"])
                print("Email:", details["email"])
                print("-------------------")

    # Search Contact
    elif choice == "3":
        search_name = input("Enter contact name to search: ")

        if search_name in contacts:
            print("Contact Found!")
            print("Phone:", contacts[search_name]["phone"])
            print("Email:", contacts[search_name]["email"])
        else:
            print("Contact not found!")

    # Update Contact
    elif choice == "4":
        update_name = input("Enter contact name to update: ")

        if update_name in contacts:
            new_phone = input("Enter new phone number: ")
            new_email = input("Enter new email: ")

            contacts[update_name]["phone"] = new_phone
            contacts[update_name]["email"] = new_email

            save_contacts()
            print("Contact updated successfully!")
        else:
            print("Contact not found!")

    # Delete Contact
    elif choice == "5":
        delete_name = input("Enter contact name to delete: ")

        if delete_name in contacts:
            del contacts[delete_name]

            save_contacts()
            print("Contact deleted successfully!")
        else:
            print("Contact not found!")

    # Exit
    elif choice == "6":
        print("Thank you for using Contact Management System!")
        break

    else:
        print("Invalid choice! Please try again.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile contact_management.py
# 
# import json
# import os
# 
# 
# def load_contacts():
#     if os.path.exists("contacts.json"):
#         with open("contacts.json", "r") as file:
#             return json.load(file)
#     return {}
# 
# 
# def save_contacts(contacts):
#     with open("contacts.json", "w") as file:
#         json.dump(contacts, file, indent=4)
# 
# 
# def main():
#     contacts = load_contacts()
# 
#     while True:
#         print("\n===== Contact Management System =====")
#         print("1. Add Contact")
#         print("2. View Contacts")
#         print("3. Search Contact")
#         print("4. Update Contact")
#         print("5. Delete Contact")
#         print("6. Exit")
# 
#         choice = input("Enter your choice: ")
# 
#         if choice == "1":
#             name = input("Enter contact name: ")
#             phone = input("Enter phone number: ")
#             email = input("Enter email: ")
# 
#             contacts[name] = {
#                 "phone": phone,
#                 "email": email
#             }
# 
#             save_contacts(contacts)
#             print("Contact added successfully!")
# 
#         elif choice == "2":
#             if not contacts:
#                 print("No contacts available!")
#             else:
#                 print("\n--- All Contacts ---")
# 
#                 for name, details in contacts.items():
#                     print("Name:", name)
#                     print("Phone:", details["phone"])
#                     print("Email:", details["email"])
#                     print("-------------------")
# 
#         elif choice == "3":
#             search_name = input("Enter contact name to search: ")
# 
#             if search_name in contacts:
#                 print("Contact Found!")
#                 print("Phone:", contacts[search_name]["phone"])
#                 print("Email:", contacts[search_name]["email"])
#             else:
#                 print("Contact not found!")
# 
#         elif choice == "4":
#             update_name = input("Enter contact name to update: ")
# 
#             if update_name in contacts:
#                 new_phone = input("Enter new phone number: ")
#                 new_email = input("Enter new email: ")
# 
#                 contacts[update_name]["phone"] = new_phone
#                 contacts[update_name]["email"] = new_email
# 
#                 save_contacts(contacts)
#                 print("Contact updated successfully!")
#             else:
#                 print("Contact not found!")
# 
#         elif choice == "5":
#             delete_name = input("Enter contact name to delete: ")
# 
#             if delete_name in contacts:
#                 del contacts[delete_name]
#                 save_contacts(contacts)
#                 print("Contact deleted successfully!")
#             else:
#                 print("Contact not found!")
# 
#         elif choice == "6":
#             print("Thank you for using Contact Management System!")
#             break
# 
#         else:
#             print("Invalid choice! Please try again.")
# 
# 
# if __name__ == "__main__":
#     main()